# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(240, 252)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.your_id_label = QtWidgets.QLabel(self.centralwidget)
        self.your_id_label.setGeometry(QtCore.QRect(20, 10, 91, 20))
        self.your_id_label.setAlignment(QtCore.Qt.AlignCenter)
        self.your_id_label.setObjectName("label")

        self.id_display_label = QtWidgets.QLabel(self.centralwidget)
        self.id_display_label.setGeometry(QtCore.QRect(20, 30, 91, 21))
        self.id_display_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.id_display_label.setObjectName("label_2")

        self.remote_id_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.remote_id_entry.setGeometry(QtCore.QRect(130, 30, 91, 20))
        self.remote_id_entry.setObjectName("lineEdit")

        self.remote_id_label = QtWidgets.QLabel(self.centralwidget)
        self.remote_id_label.setGeometry(QtCore.QRect(130, 10, 91, 20))
        self.remote_id_label.setAlignment(QtCore.Qt.AlignCenter)
        self.remote_id_label.setObjectName("label_3")

        self.connect_button = QtWidgets.QPushButton(self.centralwidget)
        self.connect_button.setGeometry(QtCore.QRect(20, 60, 201, 41))
        self.connect_button.setObjectName("pushButton")
        self.connect_button.clicked.connect(self.connect)

        self.info_panel = QtWidgets.QLabel(self.centralwidget)
        self.info_panel.setGeometry(QtCore.QRect(20, 119, 201, 111))
        self.info_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_panel.setAlignment(QtCore.Qt.AlignCenter)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RDCA"))
        self.your_id_label.setText(_translate("MainWindow", "Your ID"))
        self.remote_id_label.setText(_translate("MainWindow", "Remote ID"))
        self.connect_button.setText(_translate("MainWindow", "Connect"))

    def connect(self):
        print(self.remote_id_entry.text())

class RDP_GUI:
    def __init__(self):
        pass
    def run(self):
        import sys
        import os

        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
